# Generated by Django 4.1.7 on 2023-03-07 17:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_bio_profile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('lesson_name', models.CharField(blank=True, max_length=100)),
                ('money', models.IntegerField(blank=True, default='0')),
                ('wallet', models.IntegerField(blank=True, default='0')),
                ('activity_type', models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase')], max_length=25)),
                ('purchase_type', models.CharField(blank=True, choices=[('code', 'Code'), ('wallet', 'Wallet')], max_length=25)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
