# Generated by Django 4.1.7 on 2023-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notification_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase'), ('withdraw', 'Withdraw'), ('like', 'Like'), ('buy', 'Buy')], max_length=25),
        ),
    ]
