# Generated by Django 4.1.7 on 2023-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_notification_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('charge', 'Charge'), ('purchase', 'Purchase'), ('withdraw', 'Withdraw'), ('like', 'Like'), ('buy', 'Buy'), ('comment', 'Comment'), ('reply', 'Reply')], max_length=25),
        ),
    ]
