# Generated by Django 4.1.7 on 2023-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_notification_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
