# Generated by Django 4.1.7 on 2023-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_code_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
