# Generated by Django 4.1.7 on 2023-03-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_code_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='slug',
        ),
    ]
