# Generated by Django 4.1.7 on 2023-03-11 16:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_code_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('assigment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('student', models.CharField(blank=True, max_length=100)),
                ('assigment_name', models.CharField(blank=True, max_length=100)),
                ('no_of_applicants', models.IntegerField(blank=True, default='0')),
                ('assigment_type', models.CharField(blank=True, choices=[('test', 'Test'), ('homework', 'Homework')], max_length=25)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assigment',
                'verbose_name_plural': 'Assigments',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('assigment_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('question', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('true', models.CharField(blank=True, max_length=100)),
                ('answer1', models.CharField(blank=True, max_length=100)),
                ('answer2', models.CharField(blank=True, max_length=100)),
                ('answer3', models.CharField(blank=True, max_length=100)),
                ('answer4', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
