# Generated by Django 4.1.7 on 2023-03-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_assignment_delete_assigment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
    ]
