# Generated by Django 4.1.7 on 2023-03-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_assignment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Open',
                'verbose_name_plural': 'Opens',
            },
        ),
    ]
