# Generated by Django 4.1.7 on 2023-03-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_assignmentopen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assigment_name',
            new_name='assignment_name',
        ),
    ]
