# Generated by Django 4.1.7 on 2023-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_assigment_type_assignment_assignment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Submit',
                'verbose_name_plural': 'Submits',
            },
        ),
    ]
