# Generated by Django 4.1.7 on 2023-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_assignmentsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
            },
        ),
        migrations.AlterModelOptions(
            name='assignmentopen',
            options={'verbose_name': 'Assignment Start', 'verbose_name_plural': 'Assignment Starts'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmit',
            options={'verbose_name': 'Assignment Submit', 'verbose_name_plural': 'Assignment Submits'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Assignment Question', 'verbose_name_plural': 'Assignment Questions'},
        ),
    ]
