# Generated by Django 4.1.7 on 2023-03-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_numbers_alter_assignmentopen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
