# Generated by Django 4.1.7 on 2023-03-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_question_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
