# Generated by Django 4.1.7 on 2023-03-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_delete_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmit',
            name='answer9',
            field=models.BooleanField(default=False),
        ),
    ]
