# Generated by Django 4.1.7 on 2023-03-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='true',
            field=models.BooleanField(default=False),
        ),
    ]
