# Generated by Django 4.1.7 on 2023-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_answer_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='post_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
