# Generated by Django 4.1.7 on 2023-03-20 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_assignmentsubmit_false_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
