# Generated by Django 4.1.7 on 2023-03-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_assignmentsubmit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
