# Generated by Django 4.1.7 on 2023-03-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_code_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='student',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
