# Generated by Django 4.1.7 on 2023-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_assignmentopen_assignment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
