# Generated by Django 4.1.7 on 2023-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_assignmentsubmit_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentopen',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
