# Generated by Django 4.1.7 on 2023-04-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_post_caption_alter_post_image_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='none.mp4', upload_to='lessons'),
        ),
    ]
