# Generated by Django 4.1.7 on 2023-04-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=500)),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, choices=[('video', 'Video')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(blank=True, upload_to='lectures')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
