# Generated by Django 4.1.7 on 2023-04-06 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_part_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='id',
        ),
        migrations.AddField(
            model_name='part',
            name='part_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
