# Generated by Django 4.1.7 on 2023-04-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_part_place_alter_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='place',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('video2', 'Video2'), ('video3', 'Video3'), ('video4', 'Video4'), ('video5', 'Video5'), ('link', 'Link'), ('link2', 'Link2'), ('link3', 'Link3')], max_length=25),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('link', 'Link')], max_length=25),
        ),
    ]
