# Generated by Django 4.1.7 on 2023-04-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_part_place_alter_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
