# Generated by Django 4.1.7 on 2023-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_part_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='place',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('video2', 'Video2'), ('video3', 'Video3'), ('video4', 'Video4'), ('video5', 'Video5'), ('video6', 'Video6'), ('video7', 'Video7'), ('video8', 'Video8'), ('video9', 'Video9'), ('video10', 'Video10'), ('link', 'Link'), ('link2', 'Link2'), ('link3', 'Link3'), ('link4', 'Link4'), ('link5', 'Link5')], max_length=25),
        ),
    ]
