# Generated by Django 4.1.7 on 2023-04-10 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
