# Generated by Django 4.1.7 on 2023-04-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_info_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
    ]
