# Generated by Django 4.1.7 on 2023-04-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_info_options_assignment_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
