# Generated by Django 4.1.7 on 2023-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_assignmentresult_answer_answer1_answer_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_true',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='true',
            field=models.BooleanField(default=False),
        ),
    ]
