# Generated by Django 4.1.7 on 2023-05-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_part_assignment_id_alter_part_place_alter_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
