# Generated by Django 4.1.7 on 2023-05-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(blank=True, max_length=100)),
                ('lecture_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
