# Generated by Django 4.1.7 on 2023-05-17 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_chapterlecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlecture',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
