# Generated by Django 4.1.7 on 2023-05-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_chapterlecture_image_chapterlecture_teacher_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='id',
            new_name='chapter_id',
        ),
    ]
