# Generated by Django 4.1.7 on 2023-05-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_rename_id_chapter_chapter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_id',
            new_name='id',
        ),
    ]
