# Generated by Django 4.1.7 on 2023-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_buychapter_buylesson_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buylesson',
            options={'verbose_name': 'Lecture Purchase', 'verbose_name_plural': 'Lecture Purchases'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach1_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach1_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach2_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach2_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach3_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach3_type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('chapter', 'Chapter'), ('group', 'Group')], default='normal', max_length=25),
        ),
    ]
