# Generated by Django 4.1.7 on 2023-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_groupmember_group_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
