# Generated by Django 4.1.7 on 2023-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_grouplecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
