# Generated by Django 4.1.7 on 2023-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
