# Generated by Django 4.1.7 on 2023-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='group_images'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='group_images'),
        ),
    ]
