# Generated by Django 4.1.7 on 2023-05-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_grouplecture_options_alter_groupmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylesson',
            name='subject',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('code', 'Code'), ('lecture_code', 'Lecture Code')], default='code', max_length=25),
        ),
    ]
