# Generated by Django 4.1.7 on 2023-05-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_rename_subject_buylesson_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylesson',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('code', 'Code'), ('lecture_code', 'Lecture Code'), ('chapter', 'Chapter'), ('group', 'Group')], default='code', max_length=25),
        ),
    ]
