# Generated by Django 4.1.7 on 2023-05-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_buylesson_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='buychapter',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='buychapter',
            name='method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('code', 'Code'), ('chapter_code', 'Lecture Code')], default='code', max_length=25),
        ),
        migrations.AddField(
            model_name='buychapter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
