# Generated by Django 4.1.7 on 2023-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylesson',
            name='lecture_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
