# Generated by Django 4.1.7 on 2023-08-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_buychapter_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.IntegerField(default=1),
        ),
    ]
