# Generated by Django 4.1.7 on 2023-08-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_part_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parts_number',
            field=models.IntegerField(default=0),
        ),
    ]
