# Generated by Django 4.1.7 on 2023-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_part_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='place',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('video2', 'Video2'), ('video3', 'Video3'), ('video4', 'Video4'), ('video5', 'Video5'), ('video6', 'Video6'), ('video7', 'Video7'), ('video8', 'Video8'), ('video9', 'Video9'), ('video10', 'Video10'), ('video11', 'Video11'), ('video12', 'Video12'), ('video13', 'Video13'), ('video14', 'Video14'), ('video15', 'Video15'), ('link', 'Link'), ('link2', 'Link2'), ('link3', 'Link3'), ('link4', 'Link4'), ('link5', 'Link5'), ('assignment1', 'Assignment1'), ('assignment2', 'Assignment2'), ('assignment3', 'Assignment3'), ('assignment4', 'Assignment4'), ('assignment5', 'Assignment5')], max_length=25),
        ),
    ]
